# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kai/FocusTracker/ica

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kai/FocusTracker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kai/FocusTracker/CMakeFiles /Users/kai/FocusTracker/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kai/FocusTracker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named armaica

# Build rule for target.
armaica: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 armaica
.PHONY : armaica

# fast build rule for target.
armaica/fast:
	$(MAKE) -f CMakeFiles/armaica.dir/build.make CMakeFiles/armaica.dir/build
.PHONY : armaica/fast

#=============================================================================
# Target rules for targets named ica_bin

# Build rule for target.
ica_bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ica_bin
.PHONY : ica_bin

# fast build rule for target.
ica_bin/fast:
	$(MAKE) -f CMakeFiles/ica_bin.dir/build.make CMakeFiles/ica_bin.dir/build
.PHONY : ica_bin/fast

armaica.o: armaica.cpp.o

.PHONY : armaica.o

# target to build an object file
armaica.cpp.o:
	$(MAKE) -f CMakeFiles/armaica.dir/build.make CMakeFiles/armaica.dir/armaica.cpp.o
.PHONY : armaica.cpp.o

armaica.i: armaica.cpp.i

.PHONY : armaica.i

# target to preprocess a source file
armaica.cpp.i:
	$(MAKE) -f CMakeFiles/armaica.dir/build.make CMakeFiles/armaica.dir/armaica.cpp.i
.PHONY : armaica.cpp.i

armaica.s: armaica.cpp.s

.PHONY : armaica.s

# target to generate assembly for a file
armaica.cpp.s:
	$(MAKE) -f CMakeFiles/armaica.dir/build.make CMakeFiles/armaica.dir/armaica.cpp.s
.PHONY : armaica.cpp.s

ica.o: ica.cpp.o

.PHONY : ica.o

# target to build an object file
ica.cpp.o:
	$(MAKE) -f CMakeFiles/ica_bin.dir/build.make CMakeFiles/ica_bin.dir/ica.cpp.o
.PHONY : ica.cpp.o

ica.i: ica.cpp.i

.PHONY : ica.i

# target to preprocess a source file
ica.cpp.i:
	$(MAKE) -f CMakeFiles/ica_bin.dir/build.make CMakeFiles/ica_bin.dir/ica.cpp.i
.PHONY : ica.cpp.i

ica.s: ica.cpp.s

.PHONY : ica.s

# target to generate assembly for a file
ica.cpp.s:
	$(MAKE) -f CMakeFiles/ica_bin.dir/build.make CMakeFiles/ica_bin.dir/ica.cpp.s
.PHONY : ica.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... armaica"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ica_bin"
	@echo "... armaica.o"
	@echo "... armaica.i"
	@echo "... armaica.s"
	@echo "... ica.o"
	@echo "... ica.i"
	@echo "... ica.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

